### ISSUE TITLE
reportValidity() when not all fields are valid

### ISSUE THREAD

**Issue by eclipses** [girafffee/jfb-is-valid-inputs-field#1]
Hi, 

I would like to call reportValidty when not all fields are valid.

I've created a is_valid hidden field, I'm using in calculated fields but I would like also to show the message to the user in case for example the value inserted in a number field is not in the range between min and max.

This is my current script
```
<script>
function validateForm() { 
	this.form.reportValidity();
}

jQuery('.jet-form-builder select').on('blur', validateForm);
jQuery('.jet-form-builder input').on('keyup', validateForm);
</script>
```

**Comment by girafffee** [comment]
Hi @eclipses
Yes, currently `.reportValidity()` is called when you try to submit the form, or go to the next page if your form is split into steps. You can try Advanced Validation - in this case, the message will be displayed immediately

| In the field | In the form settings |
| -------- | --------- |
| ![image](https://github.com/girafffee/jfb-is-valid-inputs-field/assets/46720998/7aec0db2-6fa4-496b-ac9b-b15f47858c13) | ![image](https://github.com/girafffee/jfb-is-valid-inputs-field/assets/46720998/9bfdc5ce-9e13-4cc8-b24c-11846f457680) |

You can enable this mode only in one field, or globally for the entire form

**Comment by eclipses** [comment]
Hi @girafffee,

Thank you for your reply it was axactly what I was looking for.

Comple of questions are:
1) is there a simple way to enable the Advanced validatio type for all forms I'cre created as a batch? Os should I edit one by one manually?
2) My website is bilingual, when I eneable the Andvanced validation means that all message will be in English? It would be great if possible to setup for each form the language and manage the messages centrally for each language.

**Comment by girafffee** [comment]
> 1. Os should I edit one by one manually

Yes

> 2. It would be great if possible to setup for each form the language and manage the messages centrally for each language.

Currently, you can only create duplicate forms for each language and change the message in each of them.

P.S. Integration with multilingual plugins will come after other basic necessary features are implemented

**Comment by eclipses** [comment]
Thank you again, I'm closing this issue
